name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     
      - name: Run Unit tests
        run: curl -s "https://get.sdkman.io" | bash
             source "$HOME/.sdkman/bin/sdkman-init.sh"
             sdk version
             sdk install gradle 2.14.1
             gradle -v
