name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     
      - name: Run Unit tests
        run: |
             gradle wrapper
             gradlew -v
         
            
